version: '3.7'

services:
  notebook:
    image: web3anals
    container_name: web3anals
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
      - 8545:8545
      - 8080:8080
    
