[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = true

# Print the names of the compiled contracts
names = true
# Print the sizes of the compiled contracts
sizes = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config